name: 'Run Tests'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    steps:
      - name: 'Checkout Git repository with history for all branches and tags'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install, lint, and test'
        run: |
          yarn install --frozen-lockfile
          yarn test
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false &&
          contains(github.event.commits[0].message, '[ci skip]') == false

      - name: 'Upload coverage reports to Codecov'
        uses: codecov/codecov-action@v5.5.0
        with:
          fail_ci_if_error: false
          files: ./coverage/lcov.info
          flags: unittests
          verbose: false
          yml: ./codecov.yml
